app:
  host: 0.0.0.0
  port: :18000
  debug: true
  stat: true
mysql:
  master:
    dsn: root:12345678@tcp(127.0.0.1:3306)/young?charset=utf8&parseTime=True&loc=Local
  slave:
    dsn: root:12345678@tcp(127.0.0.1:3306)/young?charset=utf8&parseTime=True&loc=Local
  driver: mysql
mongo:
  addr: mongodb://127.0.0.1:27017
  authMechanism: SCRAM-SHA-1
  authSource: test
  userName: test
  passWord: 12345678
  maxPool: 10
  minPool: 5
  isLink: true
redis:
  protocol: tcp
  host: 127.0.0.1
  port: 6379
  auth:
  maxIdle: 5
  maxActive: 10
  idleTimeout: 180
  db: 8
limiter:
  speed: 5000
  concurrent: 3000
  timeout: 500